### ISSUE TITLE
QPPQ not returning results for some basins

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1163]
Empty tables for "Exceedance Probabilities of Clicked Point" and "Estimated Flows" are returned for certain basins when using the Flow Duration Curve Transfer Method. 

Link to application: https://test.streamstats.usgs.gov/ss-test-qppq/ (try Iowa)

Example of empty tables:
![image](https://user-images.githubusercontent.com/40237491/145060242-db36175c-3ab9-471a-97ac-51902838c655.png)

This seems to happen for small basins. Small basins may not have enough data to create the graphs. In the client, we could have a message in the report that says there isn't enough data or the basin is too small. We should check to ensure it is not an analytical issue in the services.

**Comment by harper-wavra** [comment]
"I think the relative stream density is causing the error on that small basin. It's coming back as undefined or -9999" - From Pete

**Comment by harper-wavra** [comment]
I think the relative stream density is causing the error on that small basin. It's coming back as undefined or -9999 - Pete M

![image](https://user-images.githubusercontent.com/59063181/151243263-995810cd-cc8d-4be1-a7a9-e140d1e27d2b.png)

**Comment by amedenblik** [comment]
This seems to only be an issue for Iowa.

**Comment by amedenblik** [comment]
This is a larger issue. If a basin doesn't return a basin characteristic (such as relative stream density), then further calculations are not computed, even if they are not dependent on the missing basin characteristic. A workaround will be needed. This is a lower priority task.

**Comment by harper-wavra** [comment]
If we are adding QPPQ to IA in the near future, this is an issue that will need to be remediated sooner rather than later. 

IN and IL both dropped relative stream density and are using the Drainage Area only regressions. IA is still using relative stream density. See [chat](https://user-images.githubusercontent.com/59063181/151242710-4e11cdf7-ca50-4e58-93ef-2b88a4649f18.png).

Looking into this more, I don't think this is apart of the larger issue. Even when I do get RSD values I am not getting plots.
For example click point: 42.91265, -94.87059, I get an RSD value but no plots.
I tested a bunch of points in IA and the most common error is a 500 error from the nssservices-qpp services. Every once in awhile when I would get a response, there were no values for either the `regressionRegions` or the `results` objects which is what is used to display the results.

I included some insomnia requests below of the different errors I am seeing in IA. 
[Insomnia_2022-01-27.zip](https://github.com/USGS-WiM/StreamStats/files/7952066/Insomnia_2022-01-27.zip)

I pulled down [AM-237](https://github.com/USGS-WiM/NSSServices/tree/AM-237) and looked into these errors a bit and did some debugging:

500 error:
In [`evaluateExtension`](https://github.com/USGS-WiM/NSSServices/blob/AM-237/NSSAgent/NSSAgent.cs#L1808) the line [`FDCXIntercept = this.getFDCXIntercept(stationInfo);`](https://github.com/USGS-WiM/NSSServices/blob/AM-237/NSSAgent/NSSAgent.cs#L1828) is returning `null`, because there is no [`D_0_XINT`](https://github.com/USGS-WiM/NSSServices/blob/0e0dd92be6dd9cf880385a8afc52cf480f59a92c/NSSAgent/NSSAgent.cs#L1876-L1886). Then when it gets into function [`getFlowsFromPublishedDuration`](https://github.com/USGS-WiM/NSSServices/blob/AM-237/NSSAgent/ServiceAgents/FDCTMServiceAgent.cs#L160) we are getting a 500 error.

No `result` response:
The JSON being sent through doesn't have an `extensions` object.

No `regressionRegion` response:
In the function [`EstimateScenarios`](https://github.com/USGS-WiM/NSSServices/blob/0e0dd92be6dd9cf880385a8afc52cf480f59a92c/NSSAgent/NSSAgent.cs#L656) the regression region gets removed because it is invalid (?) [line 673](https://github.com/USGS-WiM/NSSServices/blob/0e0dd92be6dd9cf880385a8afc52cf480f59a92c/NSSAgent/NSSAgent.cs#L673).

**Comment by harper-wavra** [comment]
It seems like sometimes when I do get a number for RSD I am still not getting plots, so this might not be apart of the larger issue.
click point: 42.91265, -94.87059 ( I get an RSD value but no plots).
It seems from the insomia requests below we are getting no values for `regressionRegions` in IA.
[Insomnia_2022-01-26.zip](https://github.com/USGS-WiM/StreamStats/files/7945509/Insomnia_2022-01-26.zip)

**Comment by amedenblik** [comment]
Closing for now. This seems to no longer be an issue. May reopen later if this appears to be a real issue again.
