### ISSUE TITLE
incorrect coordinated discharge stats

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/StreamStats#1178]
It looks like we have something squirrelly going on with Indiana's coordinated reach functionality. A delineation on the St. Joseph River at 41.72027, -86.26709 is producing a correct watershed, but somehow it is selecting the wrong coordinated stream reach (Judy Creek) and therefore is computing peakflows using the wrong equations. In the screen snip below, the watershed is in pale green, the St Joseph River coordinated reach is the darker blue line, and the Judy Creek coordinated reach is the lighter blue highlighted line. It is about 2800 feet between the confluence of these two coordinated reach lines and the watershed delineation point, so it seems like that should be far enough away from the confluence that it wouldn't be a snapping issue. 

![image](https://user-images.githubusercontent.com/59063181/153015469-62d7911d-7543-4385-ab4d-f0cee184877d.png)

I looked into how to code selects a coordinated reach a bit this afternoon. It queries this map service: https://gis.streamstats.usgs.gov/arcgis/rest/services/coordinatedreaches/, with a bounding box. The request for the point 41.72027, -86.26709 looks like https://gis.streamstats.usgs.gov/arcgis/rest/services/coordinatedreaches/in/MapServer/0/query?geometry=-86.26664545448304,41.71337381856141,-86.26754376976012,41.72717167816403&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=eqWithStrID.BASIN_NAME,eqWithStrID.DVA_EQ_ID,eqWithStrID.a10,eqWithStrID.b10,eqWithStrID.a25,eqWithStrID.b25,eqWithStrID.a50,eqWithStrID.b50,eqWithStrID.a100,eqWithStrID.b100,eqWithStrID.a500,eqWithStrID.b500&returnGeometry=false&returnIdsOnly=false&returnCountOnly=false&returnZ=false&returnM=false&returnDistinctValues=false&f=pjson. In this case it returned two reaches, Judy Creek and St. Joseph River. It looks like the [code then just takes the first reach](https://github.com/USGS-WiM/StreamStats/blob/5d7de92ac99eb48cd90c757e883361fa2205ab4d/src/Services/StudyAreaService.ts#L741) and that is what it returns. 

It seems like we could try "tightening up" the bounding box used for reach selection. I used the coordinates from the "query?geometry=" portion of the request, just to reconstruct the bounding box used for selection. It is pretty tight from east to west, but strangely stretched out north to south.

**Comment by harper-wavra** [comment]
It looks like there are two separate issues that happens sometimes. 

1. The first is the selection box to select a coordinate reach was set to a radius of 50. This resulted in sometimes receiving two reaches back from the map service and then selecting the wrong one. I set the radius to 5 and this has seemed to solve that issue.0
2.  The second is the issue with the Peak-Flow statistics not printing out in the report. We get an error in `CoordinatedReach.ts` on lines [96](https://github.com/USGS-WiM/StreamStats/blob/4d7c0aafda10987e85ee37e11f43676c9f604abb/src/Models/CoordinatedReach.ts#L96) and [102](https://github.com/USGS-WiM/StreamStats/blob/4d7c0aafda10987e85ee37e11f43676c9f604abb/src/Models/CoordinatedReach.ts#L102). The .toFixed() function can only be used on number and sometimes the map service is returning strings. See this [request](https://gis.streamstats.usgs.gov/arcgis/rest/services/coordinatedreaches/in/MapServer/0/query?geometry=-86.26700678101349,41.71951879900797,-86.2670966125412,41.72089856912815&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=eqWithStrID.BASIN_NAME,eqWithStrID.DVA_EQ_ID,eqWithStrID.a10,eqWithStrID.b10,eqWithStrID.a25,eqWithStrID.b25,eqWithStrID.a50,eqWithStrID.b50,eqWithStrID.a100,eqWithStrID.b100,eqWithStrID.a500,eqWithStrID.b500&returnGeometry=false&returnIdsOnly=false&returnCountOnly=false&returnZ=false&returnM=false&returnDistinctValues=false&f=pjson), in `features.attributes` "eqWithStrID.a500" and "eqWithStrID.b500" are both strings instead of integers.

**Comment by amedenblik** [comment]
Adding link to the Freskdesk ticket: https://streamstats.freshdesk.com/a/tickets/117248

**Comment by harper-wavra** [comment]
Fixed partially. Point 40.74997, -86.37295 should return no coordinated reach but we are still getting a rectangle bounding box instead of a square.

**Comment by amedenblik** [comment]
Note from Ryan:
"Based on Moon's reply above, we still have a problem. It doesn't seem to have the multi-selection issue if you click on a coordinated reach feature, but if you click off of a CR feature, it still seems to try and find one nearby to use instead of going to the regression equations. I went into the xml and changed the snap distance from 4 cells to 1 cell, but that didn't seem to fix the issue at this location. When I used 40.74997, -86.37295 as a delineation point (which is on the streamgrid but in a gap between CR features- see dark blue lines in the screen snip in my previous reply to Moon) it is still using the Wabash River CR equations (the stream in the cross-hatched area in the screen snip below). It should be using the regression equations in this delineation, since it isn't on a CR feature. Does the code have some other thing that is coming into play?"

The circle that is created on [this line](https://github.com/USGS-WiM/StreamStats/blob/eda2f0fc472774de99af0c442e1d748457250b6d/src/Services/StudyAreaService.ts#L725) is not giving the correct bounds on [this line](https://github.com/USGS-WiM/StreamStats/blob/eda2f0fc472774de99af0c442e1d748457250b6d/src/Services/StudyAreaService.ts#L728).
