### ISSUE TITLE
Update client for new Drupal pages

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1527]
- [x] When the user clicks the (i) button, link the user to the Drupal page (Tara will provide links).

![image](https://user-images.githubusercontent.com/40237491/216662152-469ad54f-93b2-4797-9721-54866eefe83d.png)

In the About modal:
- [x] "About the project" content should be hardcoded (link the image from Drupal)
- [x]  "State / Regional Info" should link to https://www.usgs.gov/streamstats/state-and-region-based-info
- [x] "News" should link to https://www.usgs.gov/streamstats/news
- [x] "Disclaimers" should be hardcoded (if not already)

**Comment by harper-wavra** [comment]
Drupal URLS - [StateRegion_DrupalURLs.xlsx](https://github.com/USGS-WiM/StreamStats/files/10688741/StateRegion_DrupalURLs.xlsx)

**Comment by USGSPMM3** [comment]
"About the project"

- Tara should have a new figure as of this morning to use.
- The paragraph below the figure is not correct. Purple is basin specific and/or storm drain implementations. Blue correctly indicates in development. Orange are states that have limited functionality for delineating basins and computing basin characteristics but have no flow estimates, and grey are states that are not implemented. With Tara's new map we shouldn't have any orange states.

"State/Regional Information"

- Once a state is selected, the text made me think you had not linked directly to the state because it still says "See our State and Region pages" but the link went to the actual state I was on. If it is easy to edit the text based on the state selected, that would be great to say "See the information about Idaho" or something like that.
