### ISSUE TITLE
Allow upload of all compressed files

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1611]
On https://dev.streamstats.usgs.gov/bp/, I am unable to upload [smbatch.zip](https://github.com/USGS-WiM/StreamStats/files/11345956/smbatch.zip)

![image](https://user-images.githubusercontent.com/40237491/234927206-d34baed8-1657-4c49-9f13-636f7f96fe8c.png)

**Comment by alaws-USGS** [comment]
@amedenblik I was checking into this and I'm able to complete the upload with the smbatch.zip on both Edge and Chrome. 
![image](https://github.com/USGS-WiM/StreamStats/assets/108412194/f71607c9-ae23-4571-9676-ee6c7545534e)

I tried at both the URL for dev above and through my localhost. Have you have any luck since creating this?

**Comment by amedenblik** [comment]
No, unfortunately I'm still seeing the issue! Here's a demo: https://recordit.co/BsvxjWP2tW

Maybe I'll try to tackle this one since your machine isn't able to recreate. Not sure what's going on!

**Comment by alaws-USGS** [comment]
Sounds good! Would you like me to delete the arl-1611 branch or would you like to work off of that?

**Comment by amedenblik** [comment]
Let's keep it for now; we can delete later

**Comment by amedenblik** [comment]
I think this is resolved but will reopen if we learn otherwise
