### ISSUE TITLE
Display of non-simplified basins not working

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1653]
It seems that the display of non-simplified basins is not working as described in https://github.com/USGS-WiM/StreamStats/issues/1114 and resolved in #1126.

Example: It is described in https://github.com/USGS-WiM/StreamStats/issues/1125 that 18.44253, -66.36785 should have a non-simplified basin that can be displayed. This does not seem to work on Prod:

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/5976fd3e-0658-42a1-8c7e-69768d88bfb1)

**Comment by harper-wavra** [comment]
It seems this is not being simplified because the number of vertices is 746, see https://github.com/USGS-WiM/StreamStats/blob/dev/src/Services/StudyAreaService.ts#L1161-L1185. If vertices are less than 5000, there is no need to simplify. However I am not sure why this delineation used to have more vertices.

I tested the delineation with simplify=false in the delineation request and it returned 10256 vertices and the simplify functionality in the client all worked.

**Comment by USGSPMM3** [comment]
When you zoom in to the delineation, the delineation edge should be pixelized and follow the same N,S,E,W orientation as the streamgrid. If the vertices do not follow that pattern then you are looking at a simplified basin delineation.

**Comment by harper-wavra** [comment]
In this image the red is un-simplified and yellow is simplified. 
![image](https://github.com/USGS-WiM/StreamStats/assets/59063181/c2fc725b-d763-4b58-b2dc-0c7c21cb3e6d)
