### ISSUE TITLE
Fix PDF print formatting

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats#1780]
A user has reported issues with the StreamStats report print formatting. 

![image001](https://github.com/USGS-WiM/StreamStats/assets/40237491/5fe0a125-7e65-4de5-817d-6f8c1a8fff17)

See also: #1497 (may want to complete at the same time)

Ticket: https://internal.cida.usgs.gov/jira/browse/STREAMSTAT-113

This may be related to browser type or version.

**Comment by amedenblik** [comment]
Another ticket: https://internal.cida.usgs.gov/jira/browse/STREAMSTAT-119

**Comment by amedenblik** [comment]
Another ticket: https://internal.cida.usgs.gov/jira/browse/STREAMSTAT-121

**Comment by harper-wavra** [comment]
This is also happening when printing gage some pages, 12340000 print weird, 06359000 doesn't.

**Comment by harper-wavra** [comment]
Some notes:

I have been focusing on the gagepages so I don't have to go through the whole workflow.  I am kind of thinking this is due to our column headers being too long. If you comment out the Statistics table, it will print fine. If you go further and just comment out a couple column headers in the table it still prints fine, which is why I am thinking the text might be too long and we need some kind of wrapper.

**Comment by amedenblik** [comment]
The gage plots tab is also looking worse now (not taking up the full page width)

Related to #1709

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/3aa729ac-ded7-47fb-a8df-e557860af81b)

**Comment by amedenblik** [comment]
Things to look into:
* Generate the view with html2canvas, then turn that view into a pdf with jspdf
* The WHISPERS application has code that does this
* jspdf
* pdfmake

**Comment by amedenblik** [comment]
Reportedly working again
