### ISSUE TITLE
Prepare to be delegated traffic from streamstats.usgs.gov

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#673]
Re-route users who point their browsers to http://streamstats.usgs.gov or https://streamstats.usgs.gov to https://water.usgs.gov/osw/streamstats/

**Comment by aaronstephenson** [comment]
In Route 53, I created an A record for "streamstats.usgs.gov" pointing to 34.194.77.209, which is currently StreamStatsTest. From that server, I set up a new website named "streamstats" to receive traffic from Route 53. It is only HTTP since we don't yet have an SSL certificate for this domain name. That website currently does nothing more than a simple redirect to https://water.usgs.gov/osw/streamstats/
