### ISSUE TITLE
Add WBD as a national layer - legend heading

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#705]
http://www.arcgis.com/home/webmap/viewer.html?url=https://services.nationalmap.gov/arcgis/rest/services/wbd/MapServer&source=sd

**Comment by jknewson** [comment]
pulled wbd data from nhd (https://nhd.usgs.gov/wbd.html) and added it to national mapservice

**Comment by HansVraga** [comment]
Should we have a more informative title in the Legend? "Watershed Boundary Data" (is that what WBD stands for?)
![image](https://cloud.githubusercontent.com/assets/12058013/26735343/8f183284-478f-11e7-84be-aa96322f9da1.png)

**Comment by jknewson** [comment]
I'll see what I can do, The name is served from the service, but not being read by the legend.

**Comment by jknewson** [comment]
the wbd name isn't being passed along for the legend https://streamstatstest.wim.usgs.gov/arcgis/rest/services/StreamStats/nationalLayers/MapServer/legend?f=pjson
as is defined here https://streamstatstest.wim.usgs.gov/arcgis/rest/services/StreamStats/nationalLayers/MapServer

there may be away to configure the mapservices to group this instead of serving them as separate symbology. But I'll probably need some guidance/ help

**Comment by jknewson** [comment]
It's not as straight forward as we had hoped. I'm going to punt on this. I'll leave it as an issue but change the milestone to future.

**Comment by jknewson** [comment]
fixed by overriding the legend. see issue #933
