### ISSUE TITLE
SSL cert doesn't seem to be working on test.streamstats.usgs.gov

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#752]
https://test.streamstats.usgs.gov/arcgis/rest/services/StreamStats/nationalLayers/MapServer

**Comment by aaronstephenson** [comment]
Yes, that makes sense, since until recently that server was accessed via streamstatstest.wim.usgs.gov, so it was using the *.wim.usgs.gov SSL cert. I just forgot to switch it over to the *.streamstats.usgs.gov SSL cert when we made the domain name switch.

But the switch is done now, so that link should work. I did the same on the production server.
