### ISSUE TITLE
Prepare for StreamStats v4 go-live

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/StreamStats#858]
New setup is as follows:
Test Tier:
1 EC2 for main web services.  [IIS, ArcGIS Desktop 10.5.1 /ArcHydro]
1 EC2 for ArcGIS map services.  [ArcGIS Enterprise 10.5.1, Web Adaptor]

Prod Tier:
2x load balanced EC2 for main web services. IIS, ArcGIS Desktop 10.5.1 /ArcHydro
multiple EC2 for ArcGIS map services. [ArcGIS Enterprise 10.5.1, Web Adaptor]

Tasks:

Backups:
- [x] snapshot liljohn (EC2 and attached storage)
- [x] snapshot lilrichard (EC2 and attached storage)

Setup Test Tier: (Promote lilJohn and lilRichard):
- [x] rename lilJohn to 'test' EC2 
- [x] rename lilRichard to 'testGIS' (ArcGIS server)

Setup Prod Tier:
- [x] Create new 'prod' EC2 (cloned from lilJohn/test) 2x for new load balanced 'prod' tier
- [x] Create fresh 'prodGIS' EC2 (because of issues cloning/licensive ArcGIS enterprise)

**Comment by aaronstephenson** [comment]
Done.

![image](https://user-images.githubusercontent.com/8713712/33694567-71f5a48a-dabe-11e7-84f3-da80eb1facc1.png)

### new 'prod' EC2 (cloned from lilJohn/test) 2x for new load balanced 'prod' tier
- ProdWebA (34.236.248.15)
- ProdWebB (34.232.214.56)
- StreamStatsProdWebLB (services.streamstats.usgs.gov for now, will be changed to streamstats.usgs.gov when promoted to true production)

### fresh 'prodGIS' EC2 (because of issues cloning/licensive ArcGIS enterprise)
- ProdAGS (gis.streamstats.usgs.gov and 34.194.77.209)
(this needs to have relevant AGS services published)
(this could also be load balanced if you choose)

Credentials are in keepass.

**Comment by marsmith** [comment]
Jeremy and I did the following today:
- [x] setup and tested ProdAGS
- [x] Tested ProdWebA,ProdWebB,TestWeb
- [x] redirect AGS requests to ProdAGS (so we can shutdown ProdAGSGold)

Tasks for SysOp:
- [x] move FQDN 'test.streamstats.usgs.gov' to TestWeb
- [x] assign an FQDN to TestAGS 'testgis.streamstats.usgs.gov'
- [x] Turn 'ProdAGSGold' off
- [x] Figure out transfer for Prod tier go-live.  We would like to keep the services url 'services.streamstats.usgs.gov' but are unsure what the implications are for the redirecting/etc
- [x] assist in setting up the root redirects/webconfig on prod servers I had them in there but was causing 301 errors.

**Comment by aaronstephenson** [comment]
We can keep services.streamstats.usgs.gov and just turn it into a CNAME for streamstats.usgs.gov. It would actually make the rewrites much much simpler. Let's discuss it tomorrow (Friday) before we proceed. The other steps all follow from that.

**Comment by aaronstephenson** [comment]
We're all ready to go here. Just need to get the go ahead from one of you.

**Comment by HansVraga** [comment]
Closing this issue - we've got other infrastructure related work, but V4 is live.
