### ISSUE TITLE
Downloaded basin is showing non rounded area percentage

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#984]
As I explained during my call to you, we’re finding cases where some delineations return 99% (instead of 100%) when there’s only one low flow region used.  Here are coordinates (-79.882850, 40.127995) for a point where this happened.

**Comment by jknewson** [comment]
I looked into the issue and found that the download feature, as we expected, is not displaying the rounded percent. In the streamstats report and flow computations the %area are being rounded to the nearest integer (99.94 should go to 100, where as 99.1 should go to 99 etc) whereas the downloaded is still showing the 99.94 value. I've opened a issue ticket to get that fixed, its an easy fix, but as of yet we don't have a timeline. In the meantime, hopefully the explanation of the method is helpful.

if percent area is 99.5 or less the value will be rounded down to 99% and, if additional regions are available, an area weight will be computed. If no neighbouring regions are found, the area weight is not computed and a message, similar to ('Percentage of area falls outside where region is undefined') is reported to the user.

**Comment by jknewson** [comment]
this might be better to be handled by nss percent overlay method as well

**Comment by marsmith** [comment]
This is not a v4 front-end issue as far as I can tell, needs to be fixed in the services and/or NSSservices.   I delineated a basin at the point jeremy listed and its showing correctly in the report on v4:

**Comment by kjacobsen16** [comment]
Looks like this is done in the client, which puts together the flow table [here](https://github.com/USGS-WiM/StreamStats/blob/dev/src/Services/nssService.ts#L447-L475) and exports it to the .dbf file in the modified shpwrite file [here](https://github.com/USGS-WiM/StreamStats/blob/dev/src/Assets/JS/shpwrite_modified.js).

I modified all the percent weights in the report and tables to round to 1 decimal point instead of whole percentage at Kernell's request, but looking at the point listed in this thread, we get a 99.9% weight for this basin. Is that fine or do we want to round up to 100 if it's above 99.5, as this thread says? Seems inconsistent.

@USGSPMM3 do you have any preference here?

**Comment by amedenblik** [comment]
Addressed with https://code.usgs.gov/StreamStats/web-services-and-apis/NSSServices/-/merge_requests/287
